// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment
using System;
using System.Collections.Generic;

namespace Pascal;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"Pascal.Views.Pages.HomeLandingPage", typeof(Pascal.Views.Pages.HomeLandingPage)},
        {"Pascal.Views.Pages.PdfEditPages.PdfMergePage", typeof(Pascal.Views.Pages.PdfEditPages.PdfMergePage)},
        {"Pascal.Views.Pages.PdfEditPages.PdfSplitPage", typeof(Pascal.Views.Pages.PdfEditPages.PdfSplitPage)},
        {"Pascal.Views.Pages.WindowsUpdatePage", typeof(Pascal.Views.Pages.WindowsUpdatePage)},
        {"Pascal.Views.Pages.CreditPage", typeof(Pascal.Views.Pages.CreditPage)},
    };
}
